# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 0d0766d079433d9742c464860141cb1352483c419cab33ad134a07e4be60d574558241e0a92dabd58764e070556e809a9e1fdc795eb22c474817aa170487f92d

test:
  secret_key_base: 4c5aaffc80c1f35151a7cade029964e7d6c3acf0d00d119c0d86428a2cf9f49fc15fa3aea005dac7d65ddd11023cd5a66224dff8dbaf5d62054741895219bb2d

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
